name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Sample input'
        required: false
        type: boolean
  pull_request:
    branches: [ "main" ]

jobs:
 build_and_push:

    runs-on: ubuntu-latest

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop 
      - name: Create testcontainers.properties
        run: echo "testcontainers.reuse.enable=true" > /home/runner/.testcontainers.properties

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -X -B package --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            tzdvorak/machinemanager:latest
            tzdvorak/machinemanager:${{ github.sha }}

